import {
  CONFIG_ACTION_FIELD_TYPES_ENUM,
  CONFIG_VALIDATION_LOG_LEVEL_ENUM,
  CONFIG_VALIDATION_LOG_PROPERTY_TYPES_ENUM,
  CONFIG_VALIDATION_LOG_MESSAGE_TYPES_ENUM,
} from './enums';

export type CONFIG_ACTION_FIELD_TYPE_TYPES =
  | CONFIG_ACTION_FIELD_TYPES_ENUM.LIST
  | CONFIG_ACTION_FIELD_TYPES_ENUM.STRING;

export type CONFIG_VALIDATION_LOG_LEVEL_TYPES =
  | CONFIG_VALIDATION_LOG_LEVEL_ENUM.INFO
  | CONFIG_VALIDATION_LOG_LEVEL_ENUM.WARNING
  | CONFIG_VALIDATION_LOG_LEVEL_ENUM.ERROR;

export type CONFIG_VALIDATION_LOG_MESSAGE_TYPE_TYPES =
  | CONFIG_VALIDATION_LOG_MESSAGE_TYPES_ENUM.MISSING_FIELD
  | CONFIG_VALIDATION_LOG_MESSAGE_TYPES_ENUM.WRONG_VALUE
  | CONFIG_VALIDATION_LOG_MESSAGE_TYPES_ENUM.EMPTY_LIST;

export type CONFIG_VALIDATION_LOG_PROPERTY_TYPE_TYPES =
  | CONFIG_VALIDATION_LOG_PROPERTY_TYPES_ENUM.STRING
  | CONFIG_VALIDATION_LOG_PROPERTY_TYPES_ENUM.BOOLEAN
  | CONFIG_VALIDATION_LOG_PROPERTY_TYPES_ENUM.LIST;
